import { Raleway } from 'next/font/google';
import './globals.css';
import { Nav } from '@/components/Nav';
import { MobileNav } from '@/components/MobileNav';

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  style: ['normal'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <MobileNav />
        <Nav />
        {children}
      </body>
    </html>
  );
}
